title: Material '18
description: >- # this means to ignore newlines until "baseurl:"
  A library for the Material Design 2018 edition.
# baseurl: "/material-design-18" # the subpath of your site, e.g. /blog
url: "https://martondev.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

port: 8080 # Default port
